### ISSUE TITLE
Visual mode export mapping should support exporting partial lines

### ISSUE THREAD

**Issue by dbarnett** [google/vim-syncopate#30]
If you visually select part of a line and invoke the mapping for `:SyncopateExportToClipboard`, syncopate exports the entire line to the clipboard. It would be better to export just the characters in the selection.

The mapping for this wouldn't go through `:SyncopateExportToClipboard` but would probably be a standalone function.

**Comment by chiphogg** [comment]
It would definitely be nice, but I'm not sure how to begin this one.

**Comment by dbarnett** [comment]
It's just a matter of defining a mapping something like `vmap … :<C-U>call syncopate#ExportVisual()` and having that function check the visual mark positions with `getpos("'<")` and `getpos("'>")`. The `<C-U>` is necessary to override the normal behavior of propagating the range lines into `:call`, mentioned in `:help omap-info`.

**Comment by chiphogg** [comment]
I just revisited this, and it reminded me why I thought it was hard.  Syncopate is built on top of `2html.vim`, which only operates on complete lines.

We _could_ try doing some manipulations on the resulting HTML.  In fact, we've done that before with the `<body>`-to-`<div>` hack.  But partial lines are going to be much, much harder: the characters we want to delete will be interleaved with difficult-to-predict tags.

Feel free to re-open if you see a viable way forward; I would really like to see this.
