### ISSUE TITLE
xclip: -t: No such file or directory

### ISSUE THREAD

**Issue by htfy96** [google/vim-syncopate#35]
> ERROR(shell error): Error running: xclip -t text/html -selection clipboard
xclip: -t: No such file or directory

I'm using xclip 0.12-4 on Arch Linux, and `man xclip` doesn't give out any information about `-t`. I guess `-t` is no longer supported in this version.

**Comment by chiphogg** [comment]
I've tried to find the xclip version control to see whether/when/why that option was removed, but I'm coming up empty.  I found [Arch's xclip page](https://www.archlinux.org/packages/extra/x86_64/xclip/), which lists 0.12-4 as the current version, but its upstream link points to sourceforge, which only shows version 0.12.

Any ideas?

**Comment by htfy96** [comment]
According to its `PKGBUILD`, the binary on Arch(0.12-4 where `4` is `pkgver` which doesn't change source) is built from `http://sourceforge.net/projects/xclip/files/xclip/0.12/xclip-0.12.tar.gz/download`. I browsed through the source and didn't find anything about `-t`. Maybe your distribution made extra patch on it.

**Comment by dbarnett** [comment]
I see the `--target` option added in xclip r81: http://sourceforge.net/p/xclip/code/81/

**Comment by htfy96** [comment]
Hmm... That commit was done on 2010-04-30 while `xlip-0.12` was released on 2009-09-27 and Arch only follows mainstream releases. It seems that `xclip` didn't have a release in the past 5 years.

**Comment by wsdjeg** [comment]
maybe you can try with `xsel`

**Comment by htfy96** [comment]
I have switched to `xclip-svn` in AUR, which works well. It would be better if this were mentioned in `README.md`.

**Comment by wsdjeg** [comment]
haven't used before,I install this proj just for neovim .By the way I am using fcixt's clipboard

**Comment by chiphogg** [comment]
Okay, let's figure out where we're at so we can fix this thing.

- Switching to `xclip-svn` in AUR gives a recent-enough xclip which has the `-t` option.
- `xsel` was suggested, but I don't see any way in [the man page](http://linux.die.net/man/1/xsel) to specify HTML output.  So I don't think it would be a viable alternative.

Does that sound about right?

If so, I think fixing up `README.md` should do it.  We can add a section about installing `xclip` (right now it's an undeclared dependency -- oops!).  That section can have install instructions for Ubuntu and Arch.

How does that sound?

**Comment by htfy96** [comment]
Great.

**Comment by chiphogg** [comment]
@htfy96, can you write some instructions here for how to switch to `xclip-svn` on Arch?  I've never used Arch, so I don't know.

Then I can incorporate your instructions into the pull request.  Or you can write the PR yourself if you want; let me know what you prefer.

**Comment by htfy96** [comment]
OK. I'll submit a pull request.
