### ISSUE TITLE
Official Google product

### ISSUE THREAD

**Issue by revolter** [google/vim-syncopate#38]
> DISCLAIMER: This is not an official Google product.

How is this not an official Google product if it's in the `google` organization and is featured [here][1] too?

  [1]: https://opensource.google.com/projects/vim-plugins

**Comment by dbarnett** [comment]
https://opensource.googleblog.com/2017/03/a-new-home-for-google-open-source.html

> One of the tenets of our philosophy towards releasing open source code is that "more is better." We don't know which projects will find an audience, so we help teams release code whenever possible. As a result, we have released thousands of projects under open source licenses ranging from larger products like TensorFlow, Go, and Kubernetes  to smaller projects such as Light My Piano, Neuroglancer and Periph.io. Some are fully supported while others are experimental or just for fun.

This project is in the "just for fun" category.

**Comment by dbarnett** [comment]
BTW, I sent a message to the relevant folks for the `google` organization and Google Open Source Website to suggest adding description / FAQ to clarify. Dunno if they'll feel like updating anything, though.

**Comment by revolter** [comment]
Thanks for the explanation and the message forwarding. I hope they do, as it will avoid other issues like this one
